baseURL = "https://knage.net/"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Software Developer"
    languageCode = "en-us"
    weight = 1
    [[languages.en.menu.main]]
      url = "/cv/"
      name = "Curriculum Vitae"
      weight = 100
    [languages.en.params]
      licence = "Licensed under"
      brandslicence = "All product names, logos, and brands are property of their respective owners."
      [languages.en.params.eyecatch]
        more = "Learn more"
        statement = "My dream is to use technology to build products that help people and improve quality of life"

  [languages.da]
    title = "Software Udvikler"
    languageCode = "da-dk"
    weight = 2
    [[languages.da.menu.main]]
      url = "/cv/"
      name = "Curriculum Vitae"
      weight = 100
    [languages.da.params]
      licence = "Licens"
      brandslicence = "Alle produktnavne, logoer og brands tilhører deres respektive ejere."
      [languages.da.params.eyecatch]
        more = "Læs mere"
        statement = "Mit mål er at bygge produkter der hjælper andre og øger livskvalitet"

[markup.goldmark.renderer]
unsafe= true
